spring.application.name=finance-dashboard
spring.datasource.url=jdbc:postgresql://localhost:5432/finance_dashboard
spring.datasource.username=rahul
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=financeSecretKey
jwt.expiration=86400000